#RET API
##GET ALL PROFILE

GET http://localhost:3000/profile

##  Create new Profile
### curl -X POST http://localhost:3000/profile

POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "demo1",
    "password": "1234",
    "mobile": "0135978569",
    "cardId": "1902205554897"
}
