#RET API
##GET ALL PROFILE

GET http://localhost:3000/profile

##  Create new Profile
### curl -X POST http://localhost:3000/profile

POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "demo3",
    "password": "12345",
    "mobile": "0135978565",
    "cardId": "1902205554497"
}
